### ISSUE TITLE
OZZipFile.h no longer has initialization method signatures in header.

### ISSUE THREAD

**Issue by lemonkey** [gianlucabertani/Objective-Zip#38]
https://github.com/gianlucabertani/Objective-Zip/commit/b7dcbb63b3c06c109fd02b3a52d087a33f94cec6#diff-528c3c70a8a9ce1cf813477bba5d3aee removed the init method signature from the header. 

How am I supposed to alloc and init with a filename in Objective-C now?

**Comment by gianlucabertani** [comment]
Sorry, I notice now that the README is incomplete. The initializers have just been moved to the two new categories:

* OZZipFile+Standard.h for methods throwing exceptions;
* OZZipFile+NSError.h for methods using the NSError pattern.

I'll fix the documentation as soon as possible.

**Comment by lemonkey** [comment]
Great, thanks! :+1:

**Comment by gianlucabertani** [comment]
After checking better, I think the README is actually fine as it is. An "umbrella" header has been added since version 1.0 and the README reports to use it, instead of importing headers of single classes. If you had followed this indication you wouldn't have had problems. Anyway, if you have suggestions on how to make it more clear please let me know.

**Comment by lemonkey** [comment]
Strange. I was upgrading from 0.83 and had to change my import for the refactored zip file classname but that wasn't enough apparently to be able to instantiate it with the new architecture. I'll take a look at the umbrella header, thanks. Just looking at the main diffs for the recent release threw me off.

**Comment by lemonkey** [comment]
All is fine now, thanks. Umbrella header "Objective-Zip.h" import did the trick.
